version: '3'

services:
  laravel:
    build:
      context: ./uxify-backend  # Correct context for Laravel backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./uxify-backend:/var/www/html
    depends_on:
      - vue

  vue:
    build:
      context: ./uxify-frontend  # Correct context for frontend
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./uxify-frontend:/app  # Mount frontend source code
      - node_modules:/app/node_modules  # Mount node_modules volume
    networks:
      - app-network
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  # Declare named volume for node_modules
