version: '3'

services:
  laravel:
    build:
      context: ./uxify-backend  # Correct context for Laravel backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./uxify-backend:/var/www/html
    depends_on:
      - vue

  vue:
    build:
      context: ./uxify-frontend  # Correct context for frontend
    container_name: vue_app
    ports:
      - "80:80"  # Exponer el puerto 80 para Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge